// Module included in the following assemblies:
//
// <monitoring-assembly>

[id="enabling-monitoring-microservices-{context}"]
= Enabling monitoring in microservices

Building observability into microservices externalizes the internal status of a system to enable operations teams to monitor microservice systems more effectively. It's important that microservices are written to produce metrics that can be used by operations teams when the microservices are running in production.

Metrics are emitted from a number of different places. You can obtain them from applications, the Open Liberty runtime, and the Java virtual machine (JVM). link:https://github.com/eclipse/microprofile-metrics#eclipse-microprofile-metrics[MicroProfile Metrics] provides a `/metrics` endpoint from which you can access all metrics that are emitted by the Open Liberty server and deployed applications. They can be gathered and stored in database tools, such as Prometheus, and displayed on dashboards, such as Grafana.

Metrics come in various forms, including counters, gauges, timers, histograms, and meters. You can enable metrics in your Open Liberty application with the MicroProfile Metrics feature, which defines annotations that help you quickly build metrics into your code.

For a list of all available Open Liberty metrics, see the link:https://www.openliberty.io/docs/latest/metrics-list.html[metrics reference list].

To learn how to use MicroProfile Metrics to enable and provide metrics from a microservice, see link:https://openliberty.io/guides/microprofile-metrics.html[Providing metrics from a microservice].

.Additional Resources
* link:https://www.openliberty.io/docs/latest/microservice-observability-metrics.html[Microservice observability with metrics]
