[[setting-up-git]]
= Setting up git

Open Liberty uses git to manage repositories.  This guide explains how to set up your system to connect to the proper git repositories.

https://github.com/PurpleLiberty/docs[`PurpleLiberty`^] (GitHub):: A public GitHub repo that hosts all of the Red Hat specific Open Liberty documentation.

https://gitlab.cee.redhat.com/open-liberty-documentation/docs[`Open Liberty Documentation`^] (GitLab):: A local GitLab repository used to host buildable documentation for the portal.

[[install-git]]
== Install git

If using Fedora, open your terminal and enter the proper installation command.

[discrete]
=== Fedora
[source]
----
$ yum install git (up to Fedora 21)
$ dnf install git (Fedora 22 and later)
----

[discrete]
=== Other operating systems

* https://git-scm.com/downloads[Download Git^]

[[configure-git]]
== Configuring git

Once you have git installed you'll want to set up your git account.

.Procedure
. Open *Terminal*
. Set your name and email
+
[source,options="nowrap",subs="+quotes"]
----
$ git config --global user.name "<your-name>"
$ git config --global user.email "<your-email>"
----
+
. Set your git defaults
+
[source]
----
$ git config --global pull.rebase true
$ git config --global push.default simple
----

[[fork-upstream]]
== Fork the GitLab repository

Fork the `Open Liberty Documentation` repository to create a copy under your own GitLab ID. This allows you to work on multiple features and push changes to branches in your own GitLab instance so that you do not have to worry about losing work. When you are ready, you can request the changes to be merged back into the upstream repository.

.Procedure
. Open a browser and navigate to the repository located at link:https://gitlab.cee.redhat.com/open-liberty-documentation/docs[`https://gitlab.cee.redhat.com/open-liberty-documentation/docs`^]
. Click *Fork* located in the upper right.
. Select your user account for the location of the forked repository. This creates your own copy of the repository under your own GitLab ID.

[[add-ssh-github]]
== Add your SSH keys to GitLab

If you choose to use the SSH address for your clones, you will need to add an SSH Key to GitLab first.

.Procedure
. Open *Terminal*.
. Check to see if you have a public SSH key:
+
[source]
----
$ ls ~/.ssh/
----
. If you don't have a key, generate one:
+
[source,options="nowrap",subs="+quotes"]
----
$ ssh-keygen -t rsa -C "<your-email>"
----
. Open your key in an editor:
+
[source]
----
$ cd ~/.ssh/
$ vi id_rsa.pub
----
. Copy the contents of the file to your clipboard.
. Visit link:https://gitlab.cee.redhat.com/profile/keys[https://gitlab.cee.redhat.com/profile/keys^]
. Paste your key contents into the `Key` box
. Give your key a name in the `Title` field
. Click *Add key*

[[clone-forked]]
== Clone your forked repository

Clone your forked repository to bring your GitHub repository files to your local machine. Your forked repository is now the `origin` repository for your local files.

.Procedure
. Open *Terminal*.
. Navigate to the directory where you want to create the new repository folder.
. Type the following command:
+
[source,options="nowrap",subs="+quotes"]
----
$ git clone git@gitlab.cee.redhat.com:USERNAME/eap-documentation.git
----
. Navigate to the newly created `docs` folder.
+
[source]
----
$ cd docs/
----

[[add-upstream]]
== Add the repository as a remote

Once you have your fork checked out and cloned locally, add the repository as a remote.

.Procedure
. List the current remote repositories:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@gitlab.cee.redhat.com:USERNAME/docs.git (fetch)
origin	git@gitlab.cee.redhat.com:USERNAME/docs.git (push)
----
. Add the upstream as a remote repository and fetch its contents. This allows you to check out and work with the latest source code.
+
[source]
----
$ git remote add -f upstream  git@gitlab.cee.redhat.com:open-liberty-documentation/docs.git
----
. Enter your GitLab credentials to complete the remote add process.
. Verify the new remote was added:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@gitlab.cee.redhat.com:USERNAME/docs.git (fetch)
origin	git@gitlab.cee.redhat.com:USERNAME/docs.git (push)
upstream	git@gitlab.cee.redhat.com:open-liberty-documentation/docs.git (fetch)
upstream	git@gitlab.cee.redhat.com:open-liberty-documentation/docs.git (push)
----
