[id='openliberty-sso-adapter-configuration_{context}']
= {OpenLiberty} SSO adapter configuration

The SSO adapter is the _client side_, or client to the SSO server, component that enforces security on the web resources.
In this specific case, it is the greeting service.

In {OpenLiberty}, the security configuration breaks down into two notable assets:

* The `web.xml` configuration to enact the security for the service
* The `server.xml` configuration for the keycloak adapter.

.Enacting Security using `web.xml`
[source,xml,options="nowrap",subs="attributes+"]
----
<web-app xmlns="http://java.sun.com/xml/ns/javaee" version="2.5">
  <security-constraint>
    <web-resource-collection>
      <url-pattern>/api/greeting</url-pattern> <1>
    </web-resource-collection>
    <auth-constraint>
      <role-name>example-admin</role-name> <2>
    </auth-constraint>
  </security-constraint>

  <login-config>
    <auth-method>MP-JWT</auth-method> <3>
  </login-config>

  <security-role>
    <role-name>example-admin</role-name>
  </security-role>
  
  
</web-app>
----

<1> The web context that is to be secured.
<2> The role needed to access the endpoint.
<3> Using MicroProfile JWT as the authentication method.

.MicroProfile JWT settings in `microprofile-config.properties`
[source,properties,options="nowrap",subs="attributes+"]
----
mp.jwt.verify.publickey.location=META-INF/rest-secure.pem <1>
mp.jwt.verify.issuer=${SSO_AUTH_SERVER_URL} <2>
----

<1> The location of the realm public key in PEM format. You can obtain the public key from the administration console. 
<2> The address of the {RHSSO} server (Interpolation at build time.)

.Enacting Security in `server.xml` configuration
[source,xml,options="nowrap",subs="attributes+"]
----

	<mpJwt id="secure_sso" 
    issuer="${SSO_AUTH_SERVER_URL}/realms/master" <1> 
		audiences="master_realm, account" <2>
    mapToUserRegistry="true" <3> 
		userNameAttribute="preferred_username" /> <4>
		
----

<1> The security realm to be used.
<2> The relevant audiences
<3> A setting that allows the {OpenLiberty} user registry to be used for authorization rather than the JWT token. To use the JWT token instead, the {RHSSO} administration console can be used to map the role information to the groups attribute. 
<4> The name of the attribute that the JWT token will use for the user name. 

The `web.xml` enforces protection of the Greeting service web resource endpoint. The microprofile-config.properties and server.xml files configure the security adapter to interact with {RHSSO}.
