
[id='exposing-metrics-using-prometheus-with-open-liberty_{context}']
= Exposing application metrics using Prometheus with {OpenLiberty}

In this example, you:

* Configure your application to expose metrics.
* Collect and view the data using Prometheus.

Prometheus actively connects to a monitored application to collect data; the application does not actively send metrics to a server.

.Prerequisites

* Prometheus configured to collect metrics from the application:
+
--
. Download and extract the link:https://prometheus.io/download/[archive^] with the latest Prometheus release:
+
[source,bash,options="nowrap"]
----
$ wget https://github.com/prometheus/prometheus/releases/download/v2.4.3/prometheus-2.4.3.linux-amd64.tar.gz
$ tar -xvf  prometheus-2.4.3.linux-amd64.tar.gz
----

. Navigate to the directory with Prometheus:
+
[source,bash,options="nowrap"]
----
$ cd  prometheus-2.4.3.linux-amd64
----

. Append the following snippet to the `prometheus.yml` file to specify the port where your application exposes the metrics endpoint.
+
The `scrape_interval` setting is optional and sets Prometheus to collect metrics every 5 seconds.
+
[source,yaml,options="nowrap"]
----
  - job_name: 'open-liberty'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: 'admin'
      password: 'admin'

    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['localhost:9443']

----
+
{OpenLiberty}-based applications with the MicroProfile Metrics feature enabled expose metrics at the `/metrics` endpoint.

+
The endpoint is secured by default.
To ensure that metrics collection works in your application, you must define a user registry in the Liberty configuration and include authentication information in your Prometheus metrics collection endpoint.
*
[source,xml,options="nowrap"]
----
    <basicRegistry realm="MicroProfileMetrics">
        <user name="admin" password="admin"/>
    </basicRegistry>

    <keyStore id="defaultKeyStore" password="Liberty"/>

    <administrator-role>
       <user>admin</user>
    </administrator-role>
----

--

* The Prometheus server started on `localhost`:
+
--
Start Prometheus and wait until the `Server is ready to receive web requests` message is displayed in the console.

[source,bash,options="nowrap"]
----
$ ./prometheus
----
--

.Procedure

. Collect metrics from your application:


. Annotate methods or classes with the `@org.eclipse.microprofile.metrics.annotation.Timed` annotation, for example:
+
[source,java,options="nowrap"]
----
@Path("/")
@ApplicationScoped
public class GreetingEndpoint{

    @Path("/greeting")
    @Timed(name = "greetingRequestTime",
           absolute = true,
           description = "Time needed to get the greeting")
    public String get() {
        return "Hello from a timed endpoint";
    }
}
----
+
The `@Timed` annotation is used to keep track of the time it takes to invoke the metered endpoint.

. Compile and launch your application:
+
[source,bash,opts="nowrap"]
----
$ mvn install liberty:run
----

. Invoke the traced endpoint several times:
+
[source,bash,opts="nowrap"]
----
$ curl http://localhost:9080/greeting
Hello from a timed endpoint
----

. Wait at least 15 seconds for the collection to happen, and see the metrics in Prometheus UI:
+
--
. Open the Prometheus UI at link:http://localhost:9090/[http://localhost:9090/^] and type `requests` into the _Expression_ box.
. From the suggestions, select for example `http.server.requests` and click _Execute_.
. In the table that is displayed, you can see how long it takes to invoke the metered endpoint.

Note that all metrics you created are prefixed with `application:`.
There are other metrics, automatically exposed by {OpenLiberty}.
Those metrics are prefixed with `base:` and `vendor:` and expose information about the JVM in which the application runs.
--

.Additional resources

* For additional information on using MicroProfile Metrics with Open Liberty, see link:https://openliberty.io/guides/microprofile-metrics.html[Open Liberty MicroProfile Metrics Guide^].

