:context: online

= Release Notes for Open Liberty 19.0.0.10 on Red Hat OpenShift Container Platform

== Features

:leveloffset: +1

Open Liberty 19.0.0.10 provides the useful option to configure `JSON` field names so they can best match with other data and can all be viewed in the same visualisation in the logs. The update also allows custom login modules for JCA and JMS connection factories. Give it a try in link:https://openliberty.io/about/[Open Liberty] 19.0.0.10.

In Open Liberty 19.0.0.10:

* <<jlog,Configurable JSON log field names>>
* <<jca, Custom login modules for JCA and JMS connection factories>>


[#run]
== Run your apps using 19.0.0.10

If you're using link:https://openliberty.io/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>19.0.0.10</version>
    <type>zip</type>
</dependency>
----

Or for link:https://openliberty.io/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[19.0.0.10,)'
}
----

Or if you're using Docker:

[source]
----
docker pull open-liberty
----

[#jlog]
== Configurable JSON log field names

Logging configuration in Open Liberty has been updated. Server logs can now be formatted in `basic` or `JSON` format. When logs are in `JSON` format, the sources (message, trace, accessLog, ffdc, audit) to send to `messages.log` or `console.log`/`standard-out` must be specified.

The option to configure `JSON` field names in Open Liberty is extremely useful, since Open Liberty field names may differ from other container field names. For example, an Open Liberty message is referred to by the field name `message`, while another container's message ends up in a field called `log`. Previously, two different visualisations of the messages would show in the logs on a dashboard; however, you can now modify the Open Liberty output field names. This means that they can best match with other data and can all be viewed in the same visualisation.

When logs are in `JSON` format, you can use the `jsonFieldMappings` attribute to replace default field names with new field names. To configure the new field name for all sources, use the following format:
[source]
----
defaultFieldName:newFieldName
----
To configure the new field name for a specific source, use the following format:
[source]
----
source:defaultFieldName:newFieldName
----
where `source` is the source you want to specify (such as message, trace, accessLog, ffdc, audit).

An example of configuring JSON field name by adding the following to bootstrap.properties:
[source]
----
com.ibm.ws.logging.json.field.mappings=trace:message:log,ibm_datetime:datetime
----
For more information on logging:

* link:https://openliberty.io/docs/ref/general/#logging.html[Logging and tracing]

[#jca]
== Custom login modules for JCA and JMS connection factories (jca-1.7 and jms-2.0)

An update to the Java Connector Architecture (JCA) and Java Message Service (JMS) features allows you to specify, within the server configuration, a default JAAS custom login module to use for container managed authentication to JCA and JMS connection factories.

Prior to this release, a JAAS custom login module could only be specified within the application itself for JCA and JMS connection factories. With this release, the following server configuration elements have added the ability to specify a default JAAS custom login module:

* link:https://openliberty.io/docs/ref/config/#connectionFactory.html[`connectionFactory`]
* link:https://openliberty.io/docs/ref/config/#jmsConnectionFactory.html[`jmsConnectionFactory`]
* link:https://openliberty.io/docs/ref/config/#jmsQueueConnectionFactory.html[`jmsQueueConnectionFactory`]
* link:https://openliberty.io/docs/ref/config/#jmsTopicConnectionFactory.html[`jmsTopicConnectionFactory`]

Beside these, `dataSource` element already had this capability prior to this release.

To enable the feature in the `server.xml` file:
[source,xml]
----
  <featureManager>
    <feature>appSecurity-2.0</feature>
    <feature>jca-1.7</feature>
    ... other features
  </featureManager>
  <resourceAdapter id="myAdapter" location="${server.config.dir}/resourceadapters/example-adapter.rar"/>
  <connectionFactory jndiName="eis/cf" jaasLoginContextEntryRef="customLoginEntry">
    <properties.myAdapter hostName="myhost.openliberty.io" portNumber="8765"/>
  </connectionFactory>
  <jaasLoginContextEntry id="customLoginEntry" name="customLoginEntry" loginModuleRef="customLoginModule"/>
  <jaasLoginModule id="customLoginModule" className="org.example.MyLoginModule" controlFlag="REQUIRED">
    <library>
      <file name="${server.config.dir}/myCustomLoginModule.jar"/>
    </library>
  </jaasLoginModule>
----
For more information:

* link:https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_jaas_db_auth.html[Configuring JAAS for database authentication]

:leveloffset!:

== Resolved issues

See the https://github.com/OpenLiberty/open-liberty/issues?q=label%3A%22release+bug%22+label%3Arelease%3A190010+is%3Aclosed[Open Liberty 19.0.0.10 issues that were resolved for this release].

== Fixed CVEs

For a list of CVEs that were fixed in Open Liberty 19.0.0.10, see https://openliberty.io/docs/ref/general/#security-vulnerabilities.html[security vulnerabilities].

== Known issues

See the https://github.com/OpenLiberty/open-liberty/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22release+bug%22+created%3A2019-09-06..2019-10-04+-label%3Arelease%3A190010+[list of issues that were found but not fixed during the development of 19.0.0.10].
