:context: online

= Release Notes for Open Liberty 19.0.0.10 on Red Hat OpenShift Container Platform

== Features

:leveloffset: +1

Open Liberty 19.0.0.10 provides the useful option to configure `JSON` field names so they can best match with other data and can all be viewed in the same visualisation in the logs. The update also allows custom login modules for JCA and JMS connection factories. Give it a try in link:/about/[Open Liberty] 19.0.0.10.

In Open Liberty 19.0.0.10:

* <<jlog,Configurable JSON log field names>>
* <<jca, Custom login modules for JCA and JMS connection factories>>


[#run]
== Run your apps using 19.0.0.10

If you're using link:/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>19.0.0.10</version>
    <type>zip</type>
</dependency>
----

Or for link:/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[19.0.0.10,)'
}
----

Or if you're using Docker:

[source]
----
docker pull open-liberty
----


:leveloffset!:

== Resolved issues

See the https://github.com/OpenLiberty/open-liberty/issues?q=label%3A%22release+bug%22+label%3Arelease%3A190010+is%3Aclosed[Open Liberty 19.0.0.10 issues that were resolved for this release].

== Fixed CVEs

For a list of CVEs that were fixed in Open Liberty 19.0.0.10, see https://openliberty.io/docs/ref/general/#security-vulnerabilities.html[security vulnerabilities].

== Known issues

See the https://github.com/OpenLiberty/open-liberty/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22release+bug%22+created%3A2019-09-06..2019-10-04+-label%3Arelease%3A190010+[list of issues that were found but not fixed during the development of 19.0.0.10].
