[id="configuring-logs{context}"]
= Configuring logs



// Module included in the following assemblies:
//
// <>



Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability.

The logging component is controlled through the server configuration. To configure the logging component in the `server.xml` file, use the `logging` element. It is also possible to configure logging by using `bootstrap.properties` and in some cases by using environment variables.

To learn more about Open Liberty's logging configuration, see example configurations and an index of configuration settings by source, see link:https://www.openliberty.io/docs/ref/general/#logging.html[Logging and tracing].

To learn how to configure access log settings specifically for HTTP endpoints, and to see a list of log format options, see link:https://www.openliberty.io/docs/ref/general/#access-logging.html[HTTP access logging].

.Additional resources
* link:https://openliberty.io/docs/ref/config/#logging.html[Open Liberty server configuration: Logging]
* link:https://www.openliberty.io/guides/microprofile-opentracing.html[Enabling distributed tracing in microservices]
