[id="deploying-and-packaging-applications{context}"]
= Deploying and packaging applications



// Module included in the following assemblies:
//
// <>



Open Liberty is an application server that is designed with modern cloud-native development in mind. It's fully composable, so you run only the features that you need, keeping the server lightweight. Open Liberty supports all MicroProfile and Java EE APIs and deploys to every major cloud platform, including Docker, Kubernetes, and OpenShift. To get started with Open Liberty, learn how to to run and update a simple REST microservice with the Open Liberty guide to link:https://openliberty.io/guides/getting-started.html[Deploying and packaging applications].

To package an Open Liberty server, its resources, and applications in a compressed file that you can store, distribute or deploy to a different location, use the `server package` command. To see usage examples, syntax, and options for this command, see link:https://openliberty.io/docs/ref/command/#server-package.html[server package].

.Additional resources
* https://www.openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift]
* link:https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes]
