// Module included in the following assemblies:
//
// 

[id="features-{context}"]
= Features

The Open Liberty runtime is composed of features, which are the discrete units of functionality that enable you to control the pieces of the runtime environment that are loaded into a server. You can add or remove features from the server configuration to control what functions the server can perform. Because features are pluggable and modular, you need to run only the features that your application requires. To learn more about features in Open Liberty or to see a list of all Open Liberty features, see the link:https://openliberty.io/docs/ref/feature/[feature overview].

== Using features

The Open Liberty runtime contains default configuration settings. In the `server.xml file` and any other included files, specify the features that you need, along with any additions or overrides to the default settings. For more information about the server configuration, see the link:https://openliberty.io/docs/ref/config/[server configuration overview].

Each feature is configured by using the `feature` element inside the `featureManager` element in the `server.xml` file. The following example configures the link:https://openliberty.io/docs/ref/feature/#servlet-4.0.html[Java Servlets 4.0] feature:

[source,xml]
----
<server>
  <featureManager>
    <feature>servlet-4.0</feature>
  </featureManager>
</server>
----

You can also use Open Liberty's Maven plug-in to configure features. Open Liberty features are available on link:https://search.maven.org/[Maven Central] under the `io.openliberty.features` group ID. Features that are listed as dependencies are installed by the Maven plug-in along with the Open Liberty API, SPI, and Java specification dependencies that are required for compilation. 

Import the `features-bom` artifact in the `dependencyManagement` section. This artifact provides the bill of materials (BOM) for each release version. List the features that you want to add in the `dependencies` section. The following example provides the 19.0.0.9 BOM and configures the link:https://openliberty.io/docs/ref/feature/#jdbc-4.3.html[Java Database Connectivity 4.3] feature:

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>features-bom</artifactId>
            <version>19.0.0.9</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>io.openliberty.features</groupId>
        <artifactId>jdbc-4.3</artifactId>
        <type>esa</type>
        <scope>provided</scope>
    </dependency>
</dependencies>
----

For more information about using Maven dependencies to install Open Liberty features, see link:https://openliberty.io/blog/2018/07/27/installing-features-from-maven-dependencies.html[Installing features from Maven dependencies in Open Liberty].

== Zero migration

With the Open Liberty zero migration architecture, you can update your version of Open Liberty and continue to use your existing, unmodified configuration and application files without unexpected changes in behavior. Open Liberty features add new APIs and behaviors, but new product versions continue to support your existing APIs and behaviors. An API behavior change is made available as a new version of a feature so that you can choose the appropriate feature version for your application.

.Additional resources
* https://github.com/OpenLiberty/ci.maven[OpenLiberty/ci.maven documentation]
