// Module included in the following assemblies:
//
// 

[id="features-{context}"]
= Features

The Open Liberty runtime is composed of features, which are the discrete units of functionality that enable you to control the pieces of the runtime environment that are loaded into a server. You can add or remove features from the server configuration to control what functions the server can perform. Because features are pluggable and modular, you need to run only the features that your application requires. To learn more about features in Open Liberty or to see a list of all Open Liberty features, see the link:https://openliberty.io/docs/ref/feature/[Feature overview].

== Using features

The Open Liberty runtime contains default configuration settings. Specify the features that you need, along with any additions or overrides to the default settings, in the `server.xml` file and any other included files. For more information about the server configuration, see the link:https://openliberty.io/docs/ref/config/[Server configuration overview].

Each feature is configured by using the `feature` element that is enclosed within the `featureManager` element in the `server.xml` file. The following example configures the link:https://openliberty.io/docs/ref/feature/#servlet-4.0.html[Java Servlets 4.0] feature:

[source,xml]
----
<server>
  <featureManager>
    <feature>servlet-4.0</feature>
  </featureManager>
</server>
----

== Zero-migration

With Open Liberty's zero-migration architecture, you can use existing, unmodified configuration and application files with an updated version of Open Liberty without unexpected changes in behavior. New APIs and behaviors are added in new features, and your existing APIs and behaviors are supported in new product versions. Changes in API behavior happen only in new feature versions so that you can choose the appropriate feature version for your application. These versioned features continue to be supported across Open Liberty updates.

.Additional resources

* link:https://openliberty.io/docs/ref/feature/[Open Liberty feature overview]
* link:https://openliberty.io/docs/ref/config/[Open Liberty server configuration overview]
