// Module included in the following assemblies:
//
//

[id="what-is-{context}"]
= What is Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices. With Open Liberty, it's simple to add and remove modular features from the latest versions of MicroProfile and Jakarta EE. Because of this modular runtime structure, you need to run only the features that your application needs. And if you need to move to the latest version, Open Liberty's zero-migration architecture allows you to upgrade with minimal impact to your current applications and configurations. Open Liberty is compatible with the Jakarta EE 8 Full Platform. To learn more about Open Liberty, visit the link:https://openliberty.io/[website].

Open Liberty is one of the Java runtimes available on OpenShift, and support is provided as part of a Red Hat subscription. Run Open Liberty on OpenShift to build and deploy cloud-native applications with the benefits of the OpenShift platform. For more information about using Open Liberty with OpenShift, see link:deploying-openliberty-on-openshift.adoc[Deploying Open Liberty on OpenShift].
