// Module included in the following assemblies:
//
//

[id="features-{context}"]
= Features

The Open Liberty runtime is composed of features, which are the discrete functions that enable you to control the pieces of the runtime environment that are loaded into a server. You can add or remove features from the server configuration to control what functions the server can perform. Since features are pluggable and modular, you run only the features that your application requires. To learn more about features in Open Liberty or to see a list of all Open Liberty features, see the link:https://openliberty.io/docs/ref/feature/[feature overview].

== Using features

The Open Liberty runtime contains default configuration settings. In the `server.xml file` and any other included files, specify the features that you need, along with any additions or overrides to the default settings. For more information about the server configuration, see the link:https://openliberty.io/docs/ref/config/[server configuration overview].

Each feature is configured by using the `feature` element inside the `featureManager` element in the `server.xml` file. The following example configures the link:https://openliberty.io/docs/ref/feature/#servlet-4.0.html[Java Servlets 4.0] feature:

[source,xml]
----
<server>
  <featureManager>
    <feature>servlet-4.0</feature>
  </featureManager>
</server>
----

== Zero migration

With the Open Liberty zero migration architecture, you can update your version of Open Liberty and continue to use your existing, unmodified configuration and application files, without unexpected changes in behavior. Since Open Liberty adds new APIs and behaviors through new versions of features, you can upgrade with confidence.  Changes in behavior won’t affect your existing server configuration. An API behavior change is made available as a new version of a feature so that you can choose the appropriate feature version for your application.

.Additional resources
* https://github.com/OpenLiberty/ci.maven[OpenLiberty/ci.maven documentation]
