// Module included in the following assemblies:
//
//

[id="packaging-and-deploying-applications-{context}"]
= Packaging and Deploying applications

You can use containers as a lightweight and portable way to deploy your applications or microservices in different environments. A container image is a package of the code, dependencies, and configuration that you need to run your application. To learn how to package your applications and use Docker to build container images and run containers for your applications, see link:https://openliberty.io/guides/containerize.html[Containerizing microservices].

Open Liberty supports all MicroProfile and Java EE APIs and deploys to every major cloud platform, including link:https://openliberty.io/guides/cloud-ibm.html[IBM Cloud], link:https://openliberty.io/guides/cloud-aws.html[Amazon Web Services], and link:https://openliberty.io/guides/cloud-azure.html[Azure]. To get started with Open Liberty, learn how to to run and update a simple REST microservice with link:https://openliberty.io/guides/getting-started.html[Deploying and packaging applications].

When you run Open Liberty applications on OpenShift, you combine the most flexible server runtime available to Java developers with a streamlined DevOps process and an intuitive development pipeline. For more information, see link:https://www.openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift].

.Additional resources
* link:https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes]
