// Module included in the following assemblies:
//
//

[id="what-is-openliberty-{context}"]
= What is Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.

With Open Liberty, it's easy to add and remove modular features from the latest versions of Jakarta EE and Eclipse MicroProfile. This modular structure simplifies microservice development, enabling you to run Just enough Application Server to support the features that your application needs. Furthermore, with Open Liberty zero migration architecture, you can upgrade to the latest version with minimal impact to your current applications and configurations. Open Liberty is compatible with the Jakarta EE 8 Full Platform and Web Profile specifications and with MicroProfile 3.0. For more information, see the link:https://openliberty.io/[Open Liberty website]. For the latest updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty docs].

Open Liberty is one of the Java runtimes available on OpenShift, and support is provided as part of a Red Hat subscription. Run Open Liberty on OpenShift to build and deploy cloud-native applications with the benefits of the OpenShift platform. For more information about using Open Liberty with OpenShift, see link:https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift].

== Open Liberty Versioning

The modular feature architecture of Open Liberty, in combination with zero migration, allows the incremental delivery of new function instead of the delivery of major releases with significant new function. Each release of Open Liberty is an incremental release of the previous version and follows the yy.0.0.nn version scheme. The first 2 digits indicate the year of release and the last 2 digits indicate the number of the release within that year. An incremental release is from one release to the next in the same year or from the last release of one year to the first release of the next year. For example, the 19.0.0.11 release, a release in 2019, is an incremental release of the 19.0.0.10 release, the previous release in 2019. Likewise, the 20.0.0.1 release, which is the first release of 2020, is an incremental release of the 19.0.0.12 release, which is the last release of 2019.

The publication system for this guide requires a major version. The year of publication is used instead. For example, publications of the guide in 2019 use 2019 as the major version, but the documentation is valid in years beyond 2019.
